"""Scenario 3: Flight Delay — LH2072 MUC->HAM delayed by 30 minutes.

40 passengers, ~50% connecting through HAM to domestic/European destinations.
Some passengers have tight connections that may be missed due to the delay.
Options are generated by OptionGenerator after seeding (not hardcoded here).
"""

import random
from datetime import UTC, datetime, timedelta

from sqlalchemy.ext.asyncio import AsyncSession

from app.db.tables import (
    DisruptionPassengerRow,
    DisruptionRow,
    PassengerRow,
    SegmentRow,
)
from app.seeds.passengers import compute_priority, pick_passengers

# Onward connections from Hamburg
HAM_CONNECTIONS = [
    ("LH6300", "HAM", "TXL", timedelta(hours=0, minutes=55)),
    ("LH2085", "HAM", "STR", timedelta(hours=1, minutes=10)),
    ("LH2091", "HAM", "DUS", timedelta(hours=1, minutes=5)),
    ("EW9042", "HAM", "VIE", timedelta(hours=1, minutes=35)),
    ("LH2095", "HAM", "CGN", timedelta(hours=1, minutes=0)),
    ("SK1674", "HAM", "CPH", timedelta(hours=1, minutes=10)),
    ("LH2503", "HAM", "ZRH", timedelta(hours=1, minutes=25)),
    ("BA967", "HAM", "LHR", timedelta(hours=1, minutes=40)),
]

PAX_COUNT = 40
DISRUPTION_ID = "dis-delay-001"
FLIGHT_NUMBER = "LH2072"

# Fixed profile distribution (40 pax):
# 1 HON (Business J), 2 Senator (1 Business C, 1 Eco Y),
# 5 FTL (1 Business Z, 4 Eco Y/B/H/K), 32 No Status (4 full Y/B, 28 discounted)
_DELAY_PROFILES: list[tuple[str, str]] = [
    ("hon", "J"),
    ("sen", "C"), ("sen", "Y"),
    ("ftl", "Z"), ("ftl", "Y"), ("ftl", "B"), ("ftl", "H"), ("ftl", "K"),
    ("none", "Y"), ("none", "B"), ("none", "Y"), ("none", "B"),
    ("none", "M"), ("none", "L"), ("none", "T"), ("none", "V"),
    ("none", "W"), ("none", "Q"), ("none", "M"), ("none", "L"),
    ("none", "T"), ("none", "V"), ("none", "W"), ("none", "Q"),
    ("none", "M"), ("none", "L"), ("none", "T"), ("none", "V"),
    ("none", "W"), ("none", "Q"), ("none", "M"), ("none", "L"),
    ("none", "T"), ("none", "V"), ("none", "W"), ("none", "Q"),
    ("none", "M"), ("none", "L"), ("none", "T"), ("none", "V"),
]
assert len(_DELAY_PROFILES) == PAX_COUNT

# Fallback explanation used when Gemini grounding is not available
FALLBACK_EXPLANATION = (
    "Flight LH2072 from Munich to Hamburg is delayed by approximately 30 minutes "
    "due to a late inbound aircraft. New estimated departure is 30 minutes after "
    "the originally scheduled time. Passengers with tight onward connections from "
    "Hamburg may be affected."
)

DELAY_DURATION = timedelta(minutes=30)
FLIGHT_DURATION = timedelta(hours=1, minutes=15)


async def seed(session: AsyncSession) -> str:
    """Seed passengers, segments, and disruption record.

    Options are NOT created here — they are generated by OptionGenerator
    after seeding via the simulate/auto-seed flow in main.py.
    """
    rng = random.Random(42)
    base = datetime.now(tz=UTC)
    original_departure = base + timedelta(hours=1)
    delayed_departure = original_departure + DELAY_DURATION

    disruption = DisruptionRow(
        id=DISRUPTION_ID,
        type="delay",
        flight_number=FLIGHT_NUMBER,
        origin="MUC",
        destination="HAM",
        reason="Late inbound aircraft -- LH2072 MUC-HAM delayed 30 minutes",
        explanation=FALLBACK_EXPLANATION,
        detected_at=base,
    )
    session.add(disruption)

    # Shuffle the fixed profiles for variety
    flight_profiles = list(_DELAY_PROFILES)
    rng.shuffle(flight_profiles)

    passengers = pick_passengers(
        PAX_COUNT,
        start_index=180,  # start at 181 to avoid ID overlap with other scenarios
        profile_distribution=flight_profiles,
        rng=rng,
    )

    for pid, name, bref, loyalty_tier, booking_class in passengers:
        has_connection = rng.random() < 0.5
        priority = compute_priority(loyalty_tier, booking_class)

        pax_row = PassengerRow(
            id=pid,
            name=name,
            booking_ref=bref,
            status="notified",
            priority=priority,
            loyalty_tier=loyalty_tier,
            booking_class=booking_class,
        )
        session.add(pax_row)

        # Segment 1: MUC->HAM (delayed)
        seg1 = SegmentRow(
            passenger_id=pid,
            flight_number=FLIGHT_NUMBER,
            origin="MUC",
            destination="HAM",
            departure=delayed_departure,
            arrival=delayed_departure + FLIGHT_DURATION,
            position=0,
        )
        session.add(seg1)

        # Onward connection through HAM (50% of passengers)
        # Connections have tight layovers — some may be missed due to the delay
        if has_connection:
            conn = rng.choice(HAM_CONNECTIONS)
            # Layover between 45 min and 2 hours from ORIGINAL arrival
            # With the delay, some of these become very tight or missed
            layover = timedelta(minutes=rng.randint(45, 120))
            original_arrival = original_departure + FLIGHT_DURATION
            conn_depart = original_arrival + layover
            seg2 = SegmentRow(
                passenger_id=pid,
                flight_number=conn[0],
                origin=conn[1],
                destination=conn[2],
                departure=conn_depart,
                arrival=conn_depart + conn[3],
                position=1,
            )
            session.add(seg2)

        # Link passenger to disruption
        session.add(DisruptionPassengerRow(
            disruption_id=DISRUPTION_ID, passenger_id=pid,
        ))

    await session.commit()
    return DISRUPTION_ID
