"""Scenario 2: Munich Hub Disruption — heavy snowstorm closes all MUC runways.

6 cancelled flights, ~25 passengers each = 150 total.
Options are generated by OptionGenerator after seeding (not hardcoded here).
"""

import random
from datetime import UTC, datetime, timedelta

from sqlalchemy.ext.asyncio import AsyncSession

from app.db.tables import (
    DisruptionPassengerRow,
    DisruptionRow,
    PassengerRow,
    SegmentRow,
)
from app.seeds.passengers import compute_priority, pick_passengers

# Cancelled flights departing MUC
CANCELLED_FLIGHTS = [
    ("LH1834", "MUC", "CDG", timedelta(hours=1, minutes=45)),
    ("LH1832", "MUC", "CDG", timedelta(hours=1, minutes=45)),
    ("LH456", "MUC", "FRA", timedelta(hours=1, minutes=5)),
    ("LH2030", "MUC", "FCO", timedelta(hours=1, minutes=40)),
    ("LH1856", "MUC", "BCN", timedelta(hours=2, minutes=15)),
    ("LH1610", "MUC", "ZRH", timedelta(hours=0, minutes=55)),
]

# Realistic onward connections from each destination
ONWARD_CONNECTIONS = {
    "CDG": [
        ("AF1580", "CDG", "JFK", timedelta(hours=8, minutes=30)),
        ("AF990", "CDG", "NRT", timedelta(hours=11, minutes=45)),
        ("AF1280", "CDG", "LAX", timedelta(hours=11, minutes=15)),
        ("AF258", "CDG", "SIN", timedelta(hours=12, minutes=20)),
        ("AF382", "CDG", "GRU", timedelta(hours=11, minutes=30)),
    ],
    "FRA": [
        ("LH400", "FRA", "JFK", timedelta(hours=8, minutes=45)),
        ("LH710", "FRA", "NRT", timedelta(hours=11, minutes=30)),
        ("LH452", "FRA", "ORD", timedelta(hours=9, minutes=50)),
        ("LH760", "FRA", "ICN", timedelta(hours=10, minutes=40)),
    ],
    "FCO": [
        ("AZ608", "FCO", "JFK", timedelta(hours=9, minutes=30)),
        ("AZ780", "FCO", "NRT", timedelta(hours=12)),
        ("AZ326", "FCO", "GRU", timedelta(hours=12, minutes=15)),
    ],
    "BCN": [
        ("IB6251", "BCN", "MIA", timedelta(hours=9, minutes=45)),
        ("IB6015", "BCN", "EZE", timedelta(hours=12, minutes=30)),
        ("VY8700", "BCN", "BOG", timedelta(hours=10, minutes=40)),
    ],
    "ZRH": [
        ("LX40", "ZRH", "JFK", timedelta(hours=9)),
        ("LX16", "ZRH", "SFO", timedelta(hours=11, minutes=40)),
        ("LX180", "ZRH", "BKK", timedelta(hours=10, minutes=50)),
    ],
}

PAX_PER_FLIGHT = 25
DISRUPTION_ID = "dis-snowstorm-001"

# Fixed per-flight profile distribution (25 pax):
# 1 HON (Business J/C), 2 Senator (1 Business C/D, 1 Eco Y),
# 4 FTL (1 Business Z, 3 Eco Y/B/H), 18 No Status (2 full Y/B, 16 discounted)
_SNOWSTORM_PROFILES: list[tuple[str, str]] = [
    ("hon", "J"),
    ("sen", "C"), ("sen", "Y"),
    ("ftl", "Z"), ("ftl", "Y"), ("ftl", "B"), ("ftl", "H"),
    ("none", "Y"), ("none", "B"),
    ("none", "M"), ("none", "L"), ("none", "T"), ("none", "V"),
    ("none", "W"), ("none", "Q"), ("none", "M"), ("none", "L"),
    ("none", "T"), ("none", "V"), ("none", "W"), ("none", "Q"),
    ("none", "M"), ("none", "L"), ("none", "T"), ("none", "V"),
]
assert len(_SNOWSTORM_PROFILES) == PAX_PER_FLIGHT

# Fallback explanation used when Gemini grounding is not available
FALLBACK_EXPLANATION = (
    "Due to a severe snowstorm at Munich Airport, all runways are closed "
    "and 6 departing flights have been cancelled. Estimated reopening in 6-8 hours. "
    "Affected routes: CDG (2x), FRA, FCO, BCN, ZRH."
)


async def seed(session: AsyncSession) -> str:
    """Seed passengers, segments, and disruption record.

    Options are NOT created here — they are generated by OptionGenerator
    after seeding via the simulate/auto-seed flow in main.py.
    """
    rng = random.Random(42)
    base = datetime.now(tz=UTC)
    pax_counter = 0

    disruption = DisruptionRow(
        id=DISRUPTION_ID,
        type="cancellation",
        flight_number="MUC-HUB",
        origin="MUC",
        destination="ALL",
        reason="Heavy snowstorm in Munich -- all runways closed",
        explanation=FALLBACK_EXPLANATION,
        detected_at=base,
    )
    session.add(disruption)

    for flight_idx, (flight_num, origin, dest, flight_dur) in enumerate(CANCELLED_FLIGHTS):
        departure = base + timedelta(hours=1 + flight_idx * 0.5)

        # Shuffle the fixed profiles per flight for variety
        flight_profiles = list(_SNOWSTORM_PROFILES)
        rng.shuffle(flight_profiles)

        passengers = pick_passengers(
            PAX_PER_FLIGHT,
            start_index=pax_counter,
            profile_distribution=flight_profiles,
            rng=rng,
        )
        pax_counter += PAX_PER_FLIGHT

        for pid, name, bref, loyalty_tier, booking_class in passengers:
            has_connection = rng.random() < 0.6
            priority = compute_priority(loyalty_tier, booking_class)

            pax_row = PassengerRow(
                id=pid,
                name=name,
                booking_ref=bref,
                status="notified",
                priority=priority,
                loyalty_tier=loyalty_tier,
                booking_class=booking_class,
            )
            session.add(pax_row)

            # First segment: the cancelled MUC flight
            seg1 = SegmentRow(
                passenger_id=pid,
                flight_number=flight_num,
                origin=origin,
                destination=dest,
                departure=departure,
                arrival=departure + flight_dur,
                position=0,
            )
            session.add(seg1)

            # Onward connection (60% of passengers)
            if has_connection and dest in ONWARD_CONNECTIONS:
                conn = rng.choice(ONWARD_CONNECTIONS[dest])
                conn_depart = departure + flight_dur + timedelta(hours=rng.uniform(2, 4))
                seg2 = SegmentRow(
                    passenger_id=pid,
                    flight_number=conn[0],
                    origin=conn[1],
                    destination=conn[2],
                    departure=conn_depart,
                    arrival=conn_depart + conn[3],
                    position=1,
                )
                session.add(seg2)

            # Link passenger to disruption
            session.add(DisruptionPassengerRow(
                disruption_id=DISRUPTION_ID, passenger_id=pid,
            ))

    await session.commit()
    return DISRUPTION_ID
